---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# CorrelCon Advanced Session

### Building a modularized Shiny app with the golem 📦 and html widgets

* *Session:* Data Visualization  
* *Date:* November 7th 2020, 2:30PM (UTC+1)  
* *Speaker:* Cédric Scherer (Data Visualization Designer & Computational Ecologist)


#### Outline

In this session, I introduce you to modularized Shiny apps and a library called {golem} that simplifies the process of developing roduction-grade applications. I will also give an overview of html widgets that are useful for designing your app and allow for interactive charts and an overall nice user experience. I am going to demonstrate the possibilities using our Shiny app from the LC Berlin that recently won the CorrelAidX challenge.  


### Example App with Interactive Visualizations

You can have a look at the final example application we are going to build on [shinyapps.io](https://cedric-scherer.shinyapps.io/correlcon2020_golem_html_widgets/).


#### Resources

**Books**

* "[Mastering Shiny" by Hadley Wickham](mastering-shiny.org)
* ["Engineering Production-Grade Shiny Apps" by Colin Fay et al.](engineering-shiny.org)
* ["JavaScript for R" by Joene Coene](javascript-for-r.com)

**Collections of html widgets**

* [htmlwidgets](gallery.htmlwidgets.org)
* [Awesome Shiny extensions](nanxstats/awesome-shiny-extensions)

**Packages for charts**

* [{plotly}](plot.ly/r)
* [{echarts4r}](echarts4r.john-coene.com)
* [{ggiraph}](davidgohel.github.io/ggiraph)
* [{highcharter}](jkunst.com/highcharter)
* [{dygraphs}](rstudio.github.io/dygraphs)
* [{charter}](github.com/johncoene/charter)
* [{rbokeh}](hafen.github.io/rbokeh)
* [{metricsgraphics}](hrbrmstr.github.io/metricsgraphics)
* [{rthreejs}](github.com/bwlewis/rthreejs)
* [{visnetwork}](dataknowledge.github.io/visNetwork)
* [{networkD3}](christophergandrud.github.io/networkD3/)
* [{DiagrammeR}](rich-iannone.github.io/DiagrammeR)

**Packages for tables**

* [{DT}](rstudio.github.io/DT)
* [{gt}](gt.rstudio.com)
* [{formattable}](renkun-ken.github.io/formattable)

**Packages for maps**

* [{leaflet}](rstudio.github.io/leaflet)
* [{tmap}](github.com/mtennekes/tmap)
* [{mapdeck}](symbolixau.github.io/mapdeck)
* [{echarts4r}](echarts4r.john-coene.com)

**Packages for theming**

* [{shinydashboard}](rstudio.github.io/shinydashboard/)
* [{shinydashboardPlus}](rinterface.github.io/shinydashboardPlus)
* [{fullPage}](rinterface.github.io/fullPage)
* [{bs4Dash}](rinterface.github.io/bs4Dash)
* [{shinybulma}](rinterface.github.io/shinybulma)
